<a href="https://colab.research.google.com/github/Charlene393/DeepL/blob/main/matrixBasic.ipynb" target="_parent"><img src="https://colab.research.google.com/assets/colab-badge.svg" alt="Open In Colab"/></a>

In [1]:
import numpy as np

In [2]:
revenue = np.array([[180,200,220], [24,36,40], [12,18,20]])
expenses = np.array([[80,90,100],[10,16,20],[8,10,10]])

In [4]:
profit = revenue - expenses
profit

array([[100, 110, 120],
       [ 14,  20,  20],
       [  4,   8,  10]])

In [6]:
price_per_unit = np.array([1000,400,1200])
units = np.array([[30,40,50],[5,10,15],[2,5,7]])

In [11]:
#Broadcasting
price_per_unit*units

array([[30000, 16000, 60000],
       [ 5000,  4000, 18000],
       [ 2000,  2000,  8400]])

In [13]:
#Dot product
np.dot(price_per_unit,units)


array([34400, 50000, 64400])

In [16]:
revenue_Millions = np.array([[200,220,250],[68,79,105],[110,140,180],[80,85,90]])
dollars = np.array([75])

In [17]:
convertion_to_rupees = revenue_Millions * dollars
convertion_to_rupees

array([[15000, 16500, 18750],
       [ 5100,  5925,  7875],
       [ 8250, 10500, 13500],
       [ 6000,  6375,  6750]])

In [19]:
unit_sold = np.array([[50,60,25], [10,13,5],[40,70,52]])
price = np.array([20,30,15])

In [20]:
np.dot(price, unit_sold)

array([1900, 2640, 1430])